Application/Controllers/CourceController.cs
using Application.interfaces;
using Application.Models;
using Application.Models.ViewModel;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Application.Controllers
{
    public class CourceController : Controller
     {

         public CourceController(IUniteOfWork uniteOfWork , IMapper mapper)
         {
             UniteOfWork = uniteOfWork;
             Mapper = mapper;
         }

         public IUniteOfWork UniteOfWork { get; }
         public IMapper Mapper { get; }

         public async Task<IActionResult> Index()
         {
             var MappedCource = Mapper.Map<IEnumerable<Cource>, IEnumerable<CourcesViewModel>>(await UniteOfWork.CourcesRepo.GetAllAsync());
             return View(MappedCource);
         }

         [HttpGet]
         public async Task<IActionResult> Create()
         {
             return View();
         }
         [HttpPost]
         public async Task<IActionResult> Create(CourcesViewModel cources)
         {
             if (ModelState.IsValid)
             {

                 Cource mapperCourse = Mapper.Map<CourcesViewModel,Cource >(cources);
                 await UniteOfWork.CourcesRepo.AddAsync(mapperCourse);

                 return RedirectToAction("Index");
             }
             return View(cources);

         }
         public async Task<IActionResult> Edit(int? id)
         {
             if (id == null)
                 return NotFound();
             var Cource = await UniteOfWork.CourcesRepo.GetAsync(id);
             if (Cource == null)
                 return NotFound();
             var Mappedcource = Mapper.Map<Cource, CourcesViewModel>(Cource);
             return View(Mappedcource);
         }
         [HttpPost]
         public async Task<IActionResult> Edit(int id, CourcesViewModel cources)
         {
             if (id != cources.CourcesId)
                 return NotFound();
             if (ModelState.IsValid)
             {
                 try
                 {
                     var MappedCourse = Mapper.Map<CourcesViewModel, Cource>(cources);
                     await UniteOfWork.CourcesRepo.UpdateAsync(MappedCourse);
                     return RedirectToAction("Index");
                 }
                 catch (Exception ex)
                 {
                     return View(cources);
                 }
             }
             return View(cources);
         }
         public async Task<IActionResult> Delete(int? id, Cource cource)
         {
             if (id == null)
                 return NotFound();
             var Cource = await UniteOfWork.CourcesRepo.GetAsync(id);
             if (Cource == null)
                 return NotFound();
             var MappedCource = Mapper.Map<Cource, CourcesViewModel>(Cource);
             return View(MappedCource);
         }
         [HttpPost]
         public async Task<IActionResult> Delete(int id, CourcesViewModel cources)
         {
             if (id != cources.CourcesId)
                 return NotFound();

             try
             {
                 var MappedCource = Mapper.Map<CourcesViewModel, Cource>(cources);
                 await UniteOfWork.CourcesRepo.DeleteAsync(MappedCource);
                 return RedirectToAction(nameof(Index));
             }
             catch (Exception ex)
             {
                 return View(cources);
             }
             return View(cources);
         }

   
}
}

Application/Controllers/ResultController.cs
using Application.Models.ViewModel;
using Application.Models;
using Application.Reposaitry;
using Microsoft.AspNetCore.Mvc;
using Application.interfaces;
using AutoMapper;

namespace Application.Controllers
{
    public class ResultController : Controller
    {
        public ResultController(IUniteOfWork uniteOfWork, IMapper mapper)
        {
            UniteOfWork = uniteOfWork;
            Mapper = mapper;
        }

        public IUniteOfWork UniteOfWork { get; }
        public IMapper Mapper { get; }

        public async Task<IActionResult> Index()
        {
            var MappedResult = Mapper.Map<IEnumerable<Result>, IEnumerable<ResultViewModel>>(UniteOfWork.ResultRepo.GetResultWithStudentsAndCourses());

            return View(MappedResult);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
            ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ResultViewModel result)
        {
            if (ModelState.IsValid)
            {
                Result mapperResult = Mapper.Map<ResultViewModel, Result>(result);
                await UniteOfWork.ResultRepo.AddAsync(mapperResult);
                return RedirectToAction("Index");
            }


            return View(result);

        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
            ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;
            if (id == null)
                return NotFound();
            var Result = await UniteOfWork.ResultRepo.GetAsync(id);
            if (Result == null)
                return NotFound();
            var Mappedresult = Mapper.Map<Result, ResultViewModel>(Result);


            return View(Mappedresult);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ResultViewModel result)
        {
            if (id != result.ResultId)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedResult = Mapper.Map<ResultViewModel, Result>(result);
                    await UniteOfWork.ResultRepo.UpdateAsync(MappedResult);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
                    ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;

                    return View(result);
                }
            }
            ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
            ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;


            return View(result);
        }
        public async Task<IActionResult> Delete(int? id , Result result)
        {
            ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
            ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;
            if (id == null)
                return NotFound();
            var Result = await UniteOfWork.ResultRepo.GetAsync(id);
            if (Result == null)
                return NotFound();
            var MappedResult = Mapper.Map<Result, ResultViewModel>(Result);


            return View(MappedResult);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, ResultViewModel result)
        {
            if (id != result.ResultId)
                return NotFound();

            try
            {
                var MappedResult = Mapper.Map<ResultViewModel, Result>(result);
                await UniteOfWork.ResultRepo.DeleteAsync(MappedResult);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
                ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;
                return View(result);

            }


            ViewBag.Students = UniteOfWork.StudentRepo.GetAllAsync().Result;
            ViewBag.Cources = UniteOfWork.CourcesRepo.GetAllAsync().Result;
            return View(result);


        }
        
        }
    }
    
    

Application/Controllers/StudentController.cs
using Application.interfaces;
using Application.Models;
using Application.Models.ViewModel;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Application.Controllers
{
    public class StudentController : Controller
    {
        public StudentController(IUniteOfWork uniteOfWork, IMapper mapper)
        {
            UniteOfWork = uniteOfWork;
            Mapper = mapper;
        }

        public IUniteOfWork UniteOfWork { get; }
        public IMapper Mapper { get; }

        public async Task<IActionResult> Index()
        {
            var MappedStd = Mapper.Map<IEnumerable<Student>, IEnumerable<StudentViewModel>>(await UniteOfWork.StudentRepo.GetAllAsync());
            return View(MappedStd);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(StudentViewModel student)
        {
            if (ModelState.IsValid)
            {

               Student mapperstudent = Mapper.Map<StudentViewModel, Student>(student);
               await UniteOfWork.StudentRepo.AddAsync(mapperstudent);

                return RedirectToAction("Index");
            }
            return View(student);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            var Student =await UniteOfWork.StudentRepo.GetAsync(id);
            if (Student == null)
                return NotFound();
            var Mappedstd = Mapper.Map<Student, StudentViewModel>(Student);
            return View(Mappedstd);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, StudentViewModel student)
        {
            if (id != student.StudentId)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedStd = Mapper.Map<StudentViewModel, Student>(student);
                    await UniteOfWork.StudentRepo.UpdateAsync(MappedStd);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(student);
                }
            }
            return View(student);
        }
        public async Task<IActionResult> Delete(int? id, Student student)
        {
            if (id == null)
                return NotFound();
            var Student = await UniteOfWork.StudentRepo.GetAsync(id);
            if (Student == null)
                return NotFound();
            var Mappedstd = Mapper.Map<Student, StudentViewModel>(Student);
            return View(Mappedstd);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, StudentViewModel student)
        {
            if (id != student.StudentId)
                return NotFound();
           
                try
                {
                    var MappedStd = Mapper.Map<StudentViewModel, Student>(student);
                    await UniteOfWork.StudentRepo.DeleteAsync(MappedStd);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    return View(student);
                }
            return View(student);
        }
        

    }

    }

Application/Controllers/ViewResultController.cs
using Application.interfaces;
using Application.Models.ViewModel;
using Application.Models;

using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Application.Controllers
{
    public class ViewResultController : Controller
    {
        public ViewResultController(IUniteOfWork uniteOfWork, IMapper mapper)
        {
            UniteOfWork = uniteOfWork;
            Mapper = mapper;
        }

        public IUniteOfWork UniteOfWork { get; }
        public IMapper Mapper { get; }

        public async Task<IActionResult> Index()
        {

            var MappedResult = Mapper.Map<IEnumerable<Result>, IEnumerable<ResultViewModel>>(UniteOfWork.ResultRepo.GetResultWithStudentsAndCourses());

            return View(MappedResult);
        }

    }
}
   

Application/Views/Shared/_ButtonsPartialView.cshtml
@model int


<td>
    <a class="btn btn-warning" asp-action="Edit"  asp-route-id="@Model">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Create Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cource" asp-action="Index">Add Cource</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Result" asp-action="Index">Add Result</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewResult" asp-action="Index">View Result</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>